// Generates src/generated/schema.ts from spec/openapi.yaml.
//
// The published spec asks every caller to send `api=true` (as a query
// parameter, or as a field in the request body) to say they are using a
// company API key. The SDK always authenticates that way, so it adds the flag
// to every request itself (see src/client.ts). This script removes the flag
// from the spec before generating types, so callers never see or pass it.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { parse } from 'yaml';
import openapiTS, { astToString } from 'openapi-typescript';

const specPath = new URL('../spec/openapi.yaml', import.meta.url);
const outPath = new URL('../src/generated/schema.ts', import.meta.url);
const httpMethods = ['get', 'put', 'post', 'delete', 'patch', 'options', 'head', 'trace'];

const isApiFlagParameter = (parameter) => parameter?.name === 'api' && parameter?.in === 'query';

const withoutApiFlagParameters = (parameters) =>
  Array.isArray(parameters) ? parameters.filter((parameter) => !isApiFlagParameter(parameter)) : parameters;

const stripApiFlagFromSchema = (schema) => {
  if (!schema || typeof schema !== 'object' || !schema.properties?.api) {
    return;
  }
  delete schema.properties.api;
  if (Array.isArray(schema.required)) {
    schema.required = schema.required.filter((name) => name !== 'api');
  }
};

const stripApiFlagFromOperation = (operation) => {
  operation.parameters = withoutApiFlagParameters(operation.parameters);
  for (const media of Object.values(operation.requestBody?.content ?? {})) {
    stripApiFlagFromSchema(media.schema);
    if (media.example && typeof media.example === 'object') {
      delete media.example.api;
    }
  }
};

const spec = parse(await readFile(specPath, 'utf8'));
let strippedOperations = 0;
for (const pathItem of Object.values(spec.paths ?? {})) {
  pathItem.parameters = withoutApiFlagParameters(pathItem.parameters);
  for (const method of httpMethods) {
    if (pathItem[method]) {
      stripApiFlagFromOperation(pathItem[method]);
      strippedOperations += 1;
    }
  }
}

const ast = await openapiTS(spec);
const header = '// Generated by scripts/generate.mjs from spec/openapi.yaml. Do not edit by hand.\n\n';
await mkdir(new URL('../src/generated/', import.meta.url), { recursive: true });
await writeFile(outPath, header + astToString(ast));
console.log(`Generated types for ${strippedOperations} operations.`);
